23 select filter enhancement
ContactEngineering/topobank pull request #1029
Opened 2023-11-08 19:03 UTC by IoannisNezis

This updates the filter in the digital twin select.
New filter options:
- only surfaces shared by you
- only surfaces published by you

2023-11-08 19:06 UTC, IoannisNezis commented
Did i miss something in the "git etiquette"?
And should we discuss the content of this merge request here or in the corresponding   Issue #750?

2023-11-08 19:07 UTC, pastewka requested changes
Looks good, just one comment

2023-11-08 19:07 UTC, pastewka commented on topobank/manager/utils.py
> +            _log.error(f"Invalid sharing filter: {other}")
Should this raise an exception?

2023-11-08 19:08 UTC, pastewka commented
Looks good. I would discuss the content here.

2023-11-08 19:08 UTC, pastewka commented
There are some tests that fail, please look at them and try to fix.

2023-11-08 19:17 UTC, IoannisNezis commented on topobank/manager/utils.py
> +            _log.error(f"Invalid sharing filter: {other}")
Yes, i wanted to ask which error would be appropriate.
This error can only occur if the API is used improperly.
So a ValueError?

2023-11-08 19:21 UTC, pastewka commented on topobank/manager/utils.py
> +            _log.error(f"Invalid sharing filter: {other}")
I think a `ValueError` is fine. If this happens, then I think it may trigger an internal server error. However, it should the role of the view to translate that into a proper error message.

2023-11-08 20:55 UTC, IoannisNezis commented on topobank/manager/utils.py
> +            _log.error(f"Invalid sharing filter: {other}")
Actually this code is unreachable
https://github.com/ContactEngineering/topobank/blob/de20c93ef02c4b41d5f013c003757ac65c81a038/topobank/manager/utils.py#L1008-L1027
I'll just remove this case.
Or should i still raise a Error since it would not hurt and maybe increase readability?

2023-11-08 21:28 UTC, IoannisNezis commented
Ich würde noch gerne einen test hinzufügen

2023-11-08 23:03 UTC, IoannisNezis commented
I notices something:
publishing creates a copy of a surface right?
Is it possible that this copy is shared?
Because i thing this would not be possible to model with the current schema.
Since sharing only sets a permission, a permission published surfaces have as well.

2023-11-08 23:32 UTC, IoannisNezis commented
I got no clue why "skip_postgeneration_save" broke. Any ideas?

2023-11-09 07:45 UTC, pastewka commented
> I noticed something: publishing creates a copy of a surface right? Is it possible that this copy is shared? Because i thing this would not be possible to model with the current schema. Since sharing only sets a permission, a permission published surfaces have as well.

Publishing creates a copy, but with frozen in permissions. The whole world has view permission, nobody has any of the other permissions. Resharing a published dataset does not make sense as it is visible to everyone anyway.

2023-11-09 07:47 UTC, pastewka commented
These trackstat errors can be fixed by adding the `handle_usage_statistics` fixture to the test. (Just add `handle_usage_statistics` to the list of arguments of the test. That argument is never used in the test itself.)

2023-11-13 15:22 UTC, pastewka requested changes
One remaining request, the rest looks good

2023-11-13 15:22 UTC, pastewka commented on CHANGELOG.md
> +- ENH: Added select filter options: '(shared|published) by you'
Can you tag the issue number (#750) here?

2023-11-14 09:45 UTC, IoannisNezis commented on CHANGELOG.md
> +- ENH: Added select filter options: '(shared|published) by you'
Done

2023-11-15 17:39 UTC, pastewka approved these changes

2023-11-19 18:23 UTC, pastewka approved these changes

2023-11-23 14:35 UTC, merged