ENH: Initialized migratio to direct foreign keys in django guardian
ContactEngineering/topobank pull request #1044
Opened 2023-11-25 23:21 UTC by IoannisNezis

# direct foreign keys in django guardian
When this pull request is merged the guardian permission model will automatically migrate from using generic foreign keys to real "direct" foreign keys.

## ToDo
- [x] create new model 'SurfaceUserObjectPermission'
- [x] create migration routine
- [ ] automatically invoke migration routine at startup
- [ ] check for permission integrity after migration

At the moment the new model is disabled `enabled = False` and the migration could be tested in production without consequences in case of failure.

2023-11-25 23:25 UTC, IoannisNezis commented
@pastewka In issue #1016  you said bugs in migration 'could reveal user data'.
Can you elaborate on that?
Do you mean that if the permissions are migrated incorrectly users could access Datasets they are not supposed to access?
Or is there another Problem, that i'm not aware of?

2023-11-26 09:40 UTC, pastewka commented
Hi @IoannisNezis - thanks for taking care of this.

Two comments:
* Regarding your question, data access upon incorrect migration is exactly what I mean. Note that the new direct keys will have a database constraint which the current table does not have. However, I believe there are no dangling permission entries (i.e. cleanup without the constraint has worked okay)
* Regarding the third point on your todo list, migrations run automatically in both development and production stacks so there is nothing that you need to do on your end (except for making sure the table is migrated correctly)

2023-11-26 10:20 UTC, IoannisNezis commented
I was a bit imprecise there.
With migration i did not mean the usual database migration, but the migration of the content i.e. the permissions.
My plan is to use a management command, and call it in the entrypoint, like the normal migration.

We spoke about this briefly and i understood that the migration of the database content needs to happen fully automatic.
Is that correct?

2023-11-26 10:44 UTC, pastewka commented
Don't use a management command. For an example on how to do a (complex) migration, see here:

https://github.com/ContactEngineering/topobank/blob/main/topobank/analysis/migrations/0018_auto_20230901_2303.py

You have to write a forward and possible reverse function and run it through `RunPython` after you tables are added to the database. This means this would go into the migration file you created and that is already part of this pull request.

2023-11-30 16:49 UTC, IoannisNezis commented
I put the migration in the migration file as requested.
I also implemented a management command to check the integrity of the permission migration, in case of paranoia.
The filter: 'shared_egress' was also updated to work with the new permission model.
Note that this filter option will fail as long as the new Permission Model is not enabled.

That's also why the test fails,
how should we handle this?
- enable new Permission Model?
- update filter in separate PR?
- ignore failing test?

2023-12-04 08:45 UTC, pastewka requested changes

2023-12-04 08:45 UTC, pastewka commented on topobank/manager/models.py
> +    enabled = False
Please simply enable

2023-12-05 14:49 UTC, IoannisNezis commented on topobank/manager/models.py
> +    enabled = False
done

2023-12-05 17:03 UTC, pastewka commented
This looks good @IoannisNezis - but there seems to be one remaining issue in one of the tests

2023-12-06 10:51 UTC, IoannisNezis commented
Yes, the shared_egress filter included publicized datastets.
Should be fixed now.

2023-12-06 11:02 UTC, IoannisNezis commented
I added a `MAINT` instead of a `ENH` to the CHANGELOG, since it does not introduce a new feature but improves a existing feature.
Is that a correct usage of change types?

2023-12-09 11:01 UTC, merged