ENH: Properties for digital surface twins
ContactEngineering/topobank pull request #1057
Opened 2023-12-13 15:17 UTC by IoannisNezis

When this PR is done, digital surface twins have properties attached to them.
See #904 for more details.

- [x] Editable Properties Tab
- [x] Only editable if permissions are given 
- [x] sensible representation of properties in a database
    - [x] categorical or numerical
    - [x] name with Tagulous
    - [x] units with Tagulous
- [x] Validate Model
- [x] Serializer
- [x] Unit validation
- [x] Tests

**Optional**
- [ ] form validation

2023-12-20 17:36 UTC, IoannisNezis commented
Design example: Obsidian
![2023-12-20_18-34](https://github.com/ContactEngineering/topobank/assets/74186504/066d0650-bb37-4b3e-90cb-171de479dd50)

2023-12-20 17:49 UTC, pastewka commented
Looks good!

2023-12-20 18:26 UTC, IoannisNezis commented
Here is what i came up with to copy this:
![2023-12-20_19-25_1](https://github.com/ContactEngineering/topobank/assets/74186504/14d43c94-7233-4dbd-b6b0-3ee4edc22348)
![2023-12-20_19-25](https://github.com/ContactEngineering/topobank/assets/74186504/67a5f620-ffed-40d1-bb49-5f36f76bc1ed)

2023-12-20 18:52 UTC, pastewka commented
Looks good!

2023-12-20 19:16 UTC, IoannisNezis commented
I changed the way the "discard" "save" button looks:
![2023-12-20_20-14](https://github.com/ContactEngineering/topobank/assets/74186504/8864eff6-a5a9-468f-a148-e90e2bd80694)
![2023-12-20_20-14_1](https://github.com/ContactEngineering/topobank/assets/74186504/ddd199a1-c1e8-402c-a500-6ba40813491b)

I also want to add a [tooltip](https://getbootstrap.com/docs/4.6/components/tooltips/) to those buttons.
But this requires to add a 3rd party lib "Popper" and i wanted to get some feedback before.
Any Opinions?

2023-12-20 19:21 UTC, pastewka commented
Please keep the text for those. Icons only if there is no space.Am 20.12.2023 20:16 schrieb Ioannis Nezis ***@***.***>:
I changed the way the "discard" "save" button looks:
2023-12-20_20-14.png (view on web)
2023-12-20_20-14_1.png (view on web)
I also want to add a tooltip to those buttons.
But this requires to add a 3rd party lib "Popper" and i wanted to get some feedback before.
Any Opinions?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2023-12-21 00:17 UTC, IoannisNezis commented
Alright 👍
Is the "SAVE" intentionally all caps?
And should the edit button also be text?

2024-01-10 18:04 UTC, IoannisNezis commented on topobank/manager/models.py
> +    properties = models.TextField(default="[]")
Currently i store properties in a TextField

2024-01-10 18:04 UTC, IoannisNezis commented on topobank/frontend/manager/SurfaceProperties.vue
> +        properties: JSON.stringify(properties.value)
In the TextField i store a JSON string of the properties.
This is just a temporary soloution and should be changed!

2024-01-10 18:09 UTC, IoannisNezis commented
The test fail because the api response now contains the 'properties' field.
This is a easy fix, but i would like to wait until the properties are stored properly.

2024-01-24 21:22 UTC, pastewka commented
> The test fail because the api response now contains the 'properties' field. This is a easy fix, but i would like to wait until the properties are stored properly.

The API tests are a bit stupid anyway, it would be good if we could think of a way to simplify. It is very annoying to add those fields manually to every test.

2024-01-28 20:54 UTC, pastewka requested changes

2024-01-28 20:54 UTC, pastewka commented on topobank/manager/models.py
> +    def save(self, *args, **kwargs):
Please add a check that unit has to be None if value is categorical.

2024-01-28 20:54 UTC, pastewka commented on topobank/manager/models.py
> +    properties = models.ManyToManyField(Property)
It this the right relationship? Isn't it a one-to-many relationship, as a surface can have many properties but a property can only belong to one surface?

2024-01-28 20:54 UTC, pastewka commented on topobank/manager/models.py
> +    properties = models.ManyToManyField(Property)
This would mean the property has a `Surface` as a `ForeignKey`. Then you can also add `on_delete=CASCADE` to delete properties when the `Surface` disappears.

2024-01-28 20:54 UTC, pastewka commented on topobank/manager/serializers.py
> +        if not (isinstance(value, str) or isinstance(value, float) or isinstance(value, int)):
Please also check that `unit` is None if `value` is categorical (i.e. `str`)

2024-01-28 20:54 UTC, pastewka commented on topobank/manager/serializers.py
> +    def to_representation(self, value):
`django-rest-framwork` has no canned implementation of this?

2024-01-28 21:44 UTC, pastewka commented
@IoannisNezis I've added a couple of comments and a (non-functional) example test in the new file `test_properties.py`.

I think you need to switch from many-to-many to a one-to-many relationship where the property has a `ForeignKey` to surface. The serializer then also needs the surface like here:

https://github.com/ContactEngineering/topobank/blob/dc540ae1856ccb6558db80a6dfab7ac42a9e504e/topobank/manager/serializers.py#L92

In the test you can then create a property like here:

https://github.com/ContactEngineering/topobank/blob/dc540ae1856ccb6558db80a6dfab7ac42a9e504e/topobank/manager/tests/utils.py#L30

2024-01-29 12:50 UTC, IoannisNezis commented on topobank/manager/models.py
> +    properties = models.ManyToManyField(Property)
Yeah you are probably right.
I think i chose this because i did not know how to create the serialize-field for `properties` in the `Surface` serializer.
I'll change this.

2024-01-29 12:51 UTC, pastewka commented on topobank/manager/serializers.py
> +    def to_representation(self, value):
Sounds good. It may not exist.

2024-01-29 12:52 UTC, pastewka commented on topobank/manager/models.py
> +    properties = models.ManyToManyField(Property)
If you create a `ForeignKey`, then you get an automatic (implicit) field in the related dataset. For example, if you add a `ForeignKey` to `Surface`, then surface gets an attribute `property_set` (named automatically, which can be changed but I've never done this) that allows to access all properties.

2024-01-29 12:53 UTC, pastewka commented on topobank/manager/models.py
> +    properties = models.ManyToManyField(Property)
More here: https://docs.djangoproject.com/en/5.0/topics/db/examples/many_to_one/ - essentially you can simply add `topography_set` to the `Surface`-serializer

2024-01-31 17:12 UTC, IoannisNezis commented on topobank/manager/models.py
> +    def save(self, *args, **kwargs):
I refactored this into a seperate funktion that i call at `save`.
I don't think the setter for value is the right place to check the validity of unit.

I also added the invariant: if the value is `numerical` -> `unit` is not None (but can be blank)
Here ist the docstring explaing what i want to do:
``` python
    def validate(self):
        """
        Checks the invariants of this Model.
        If any invariant is broken, a ValueError is raised

        Invariants:
        - 1. `value_categorical` or `value_numerical` are `None`
        - 2. `value_categorical` or `value_numerical` are not `None`
        This results in a 'XOR' logic and exaclty one of the value fields has to hold a value
        - 3. if `value_categorical` is not `None`, unit is `None`
        - 4. if `value_numerical` is not `None`, unit is not `None`
        This enforces the definition of a categorical values -> no units.

        Note that the `unit` field can be blank (`""`).
        `unit` == `None` and `unit` == `""`, are not the same.
        The first means that the value has no unit, the second that the value has a dimensionless unit."""
```

2024-01-31 22:22 UTC, pastewka commented on topobank/manager/models.py
> +    def save(self, *args, **kwargs):
Looks good. There is also a `ValidationError`, but `ValueError` also works.

2024-02-01 21:32 UTC, IoannisNezis commented on topobank/manager/models.py
> +    properties = models.ManyToManyField(Property)
done.
I also changed the reverse lookup name to `peoperties`.
This is done with the `related_name` keyword.

2024-02-01 22:26 UTC, IoannisNezis commented on topobank/manager/serializers.py
> +    def to_representation(self, value):
I checked for a while and also asked a sertan AI for help.
But this solution is still the cleanest version in my Opinion.
I'm also curious if there is a smoother way, but for now this is fine i think.
Its very readable and just a bit verbose but does the job perfectly.

2024-02-02 06:57 UTC, pastewka commented on topobank/manager/serializers.py
> +    def to_representation(self, value):
No objections!

2024-02-28 17:34 UTC, IoannisNezis commented on topobank/manager/serializers.py
> +        if not (isinstance(value, str) or isinstance(value, float) or isinstance(value, int)):
I added validation for this in the serializer.

It bothers me a bit that there is some code duplication now, but since we represent 'dimensionless' values differently internally and externally this is fine for me...

2024-03-10 15:43 UTC, merged