GUI Cosmetics
ContactEngineering/TopoBank pull request #645
Opened 2021-04-28 18:38 UTC by pastewka

* Added a topobank-info-box style to be used for information context
* Renamed "Topography" to "Measurement", closes #587 
* Updated layout of contact mechanics calculations, now uses pills on the left. closes #634

2021-04-29 07:17 UTC, pastewka commented
Hi @mcrot - there is an issue with this that I just opened #646 - can you give advise how to resolve it?

2021-04-29 07:43 UTC, pastewka commented
Hi @mcrot - I think I figured it out... but it needs your review

2021-04-29 09:24 UTC, mcrot commented on topobank/templates/manager/surface_detail.html
> +                  Each of the blocks below represent one measurement.
"represents"

2021-04-29 09:37 UTC, mcrot commented on topobank/analysis/views.py
> -from bokeh.models.formatters import FuncTickFormatter
This breaks the contact plots. It creates an exception when pressing a point in the contact plot:
```python
  File "/opt/conda/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/topobank/analysis/views.py", line 1277, in contact_mechanics_data
    'contact-pressure': _contact_mechanics_geometry_figure(
  File "/app/topobank/analysis/views.py", line 1153, in _contact_mechanics_geometry_figure
    colorbar.formatter = FuncTickFormatter(code="return format_exponential(tick);")
NameError: name 'FuncTickFormatter' is not defined
```

2021-04-29 09:54 UTC, mcrot commented on topobank/analysis/views.py
> -                    title=r'Displacem.', value_unit=unit,
Now "None (µm)" is printed there .. this is not what we want?

2021-04-29 09:56 UTC, mcrot commented on topobank/analysis/views.py
> -                    title=r'Displacem.', value_unit=unit,
Same for "Gap", for contact pressure it's "None (None)". For the latter the unit should be "E*" as we discussed in #592 .

2021-04-29 10:05 UTC, mcrot requested changes
We need to improve some more things:
- [x] contact plot does not fully work any more due to missing import, try pressing a point
- [ ] colorbar labels and units in the contact plot details are broken (see single comments)
- [ ] there are several more places where "topography" is used and it not replaced by "measurement": Buttons in Analysis plots, table for special values,INFORMATION sheet in Excel files, text files from analysis, landing page of the site, maybe also subject type in task  information (would need to change "label()" method in classes), maybe also in warnings in contact plots
- [ ] we should not include changes of directory `.idea` in this PR, let's decide separately about the Python interpreter used

I would also like to discuss, probably that's easier in person:
- the text over the gallery is more informative now, but in my opinion visually less appealing; can we change this, e.g. with some box, more padding etc? I've liked the alert-info box  before, maybe we can use sth. similar?
- the new contact plot layout looks nicer than before - how important is to compare e.g. the displacement of different loads? This was easier in the version before, because both plots were visible at the same time. Resizing in the browser does not work here, so the user has to scroll up and down.

2021-04-30 08:33 UTC, mcrot commented on topobank/analysis/views.py
> -                    title=r'Displacem.', value_unit=unit,
Suggestion: With the new layout the physical quantity is visible on the left, so it would be sufficient to just display
the unit over the colorbar?

2021-04-30 08:36 UTC, mcrot commented on topobank/analysis/views.py
> -from bokeh.models.formatters import FuncTickFormatter
Fixed.

2021-04-30 08:37 UTC, mcrot commented on topobank/templates/manager/surface_detail.html
> +                  Each of the blocks below represent one measurement.
Fixed.

2021-04-30 08:58 UTC, mcrot commented on topobank/templates/manager/surface_detail.html
> +                  This surface has no measurements yet.
In case that there are no topographies yet both the bandwidth plot and the gallery show a little info text.

Now this is displayed in two different ways: For the gallery with class "topobank-info-text" and for bandwidth plot with "alert-info". I think this should be consistent and "alert-info" is a better here, because a user action is required in order to see something. What do you think?

2021-04-30 09:10 UTC, pastewka commented on topobank/templates/manager/surface_detail.html
> +                  This surface has no measurements yet.
Okay, alert-info is fine with me here.

2021-05-03 08:42 UTC, pastewka commented
Some "topographies" may be left, we will update as we find them in the code or the interface. Most should have been renamed to "measurements".

@mcrot - Can you have a look at this PR again?

2021-05-03 08:43 UTC, pastewka commented
Hang on @mcrot - I still need to update the CSS for the Bokeh tabs

2021-05-03 09:51 UTC, pastewka commented
Okay, I've updated the size of the Bokeh tabs and buttons - @mcrot you can have another look at this

2021-05-03 11:43 UTC, mcrot commented on topobank/templates/tabnav/tabs.html
> +              <i class="fa fa-download"></i> Download selected surfaces
What I have implemented here is not the downloaded of the selected surfaces, but
the download of all surfaces which are related to the selection. That means 
- if a topography is selected, its surface is downloaded
- if a tag is selected, all surfaces are downloaded which have surfaces or topographies with this tag

So think "selected surfaces" is misleading here. Maybe there is a better word?

2021-05-03 11:55 UTC, mcrot commented on topobank/templates/analysis/contactmechanics_card_detail.html
> +                                   Calcula  tions can assume that the surface repeats periodically or that it is pushing down on a nonperiodic,
Is this word warp intended? Or a hyphen needed?

2021-05-03 12:00 UTC, mcrot commented
There are some more occurences of "topographies" I haven't seen before, at least on sharing info page and help page. I' have a look at that.

2021-05-03 12:31 UTC, pastewka commented
> There are some more occurences of "topographies" I haven't seen before, at least on sharing info page and help page. I' have a look at that.

Okay, thanks!

2021-05-03 12:32 UTC, pastewka commented
There is also a problem with the tests, I'll have a look at those. It's related to the renaming I think.

2021-05-03 12:41 UTC, mcrot requested changes
Fine for me, except of the naming of the new download button. Please see my comment,
I think the old label was more correct in specifying what the button does.

And there is one more comment about a missing hyphen or broken word, I don't know what was intended there.

2021-05-03 14:16 UTC, pastewka commented on topobank/templates/tabnav/tabs.html
> +              <i class="fa fa-download"></i> Download selected surfaces
I changed this because "related" is confusing, what is a "related" surface? I understand what you mean but the average user will not. I think selected is good enough. I understand that this includes measurements that my not have been selected, but would not emphasize this in the GUI.

2021-05-03 14:18 UTC, pastewka commented on topobank/templates/analysis/contactmechanics_card_detail.html
> +                                   Calcula  tions can assume that the surface repeats periodically or that it is pushing down on a nonperiodic,
No this is a bug...

2021-05-03 14:32 UTC, pastewka commented on topobank/templates/tabnav/tabs.html
> +              <i class="fa fa-download"></i> Download selected surfaces
We could just remove the "selected" -> "Download surfaces"

2021-05-03 14:33 UTC, pastewka commented
I've renamed the download thing to just "Download surfaces". I've also updated the tests.

2021-05-03 16:42 UTC, mcrot approved these changes

2021-05-03 16:42 UTC, mcrot commented
Thank you!

2021-05-03 16:42 UTC, merged