Change RMS value table to show generic roughness parameters
ContactEngineering/TopoBank pull request #654
Opened 2021-05-05 16:18 UTC by mcrot

The renaming of the analysis function will be done later: #653 .

Could you have a look:
- How can curvature values be calculated? The method `rms_curvature_from_profile` is not available for uniform line scans and for 2D data.
- When to use "RMS gradient" and "RMS Slope" as quantity names?
- Is the list of values correct and complete? See `functions.py`

2021-05-05 19:02 UTC, pastewka requested changes

2021-05-05 19:02 UTC, pastewka commented on topobank/analysis/functions.py
> +        result.extend([
That's correct, it doesn't exist yet. We should implement this at some point but I don't think it is crucial that we have this now.

2021-05-05 19:02 UTC, pastewka commented on topobank/analysis/functions.py
> +                'from': '',
This should be `FROM_2D`

2021-05-05 19:02 UTC, pastewka commented on topobank/analysis/functions.py
>                  'direction': 'x',
The gradient has no direction. This also means the next entry needs to be removed.

2021-05-05 19:02 UTC, pastewka commented on topobank/analysis/functions.py
> +                'value': topography.rms_slope_from_profile(),
Looks good, but this exists also for 2D topographies, and there it can be computed in x and y direction. Those two entries should be added to the 2D case.

2021-05-06 07:29 UTC, mcrot commented on topobank/analysis/functions.py
> +    except Exception:
Yes!

2021-05-06 07:39 UTC, mcrot commented on topobank/analysis/functions.py
> +        result.extend([
I assume you mean `rms_curvature_from_profile` here for uniform line scans and for 2D.

2021-05-06 07:41 UTC, mcrot commented on topobank/analysis/functions.py
> +                'from': '',
Okay, thanks.

2021-05-06 07:42 UTC, mcrot commented on topobank/analysis/functions.py
> +                'value': topography.rms_slope_from_profile(),
Added.

2021-05-06 08:01 UTC, pastewka commented
Hi @mcrot - the gradient thing is still wrong, I'll edit it locally and push it to this branch

2021-05-06 08:08 UTC, pastewka commented
I just pushed this here

2021-05-06 08:11 UTC, mcrot commented
I hadn't pushed it yet..

2021-05-06 08:24 UTC, pastewka commented
Okay

2021-05-06 08:26 UTC, pastewka commented
I was marked as resolved - that's why I thought this was current.

2021-05-06 09:31 UTC, mcrot commented
> I was marked as resolved - that's why I thought this was current.

Yes, thanks for checking again! I'm not sure yet about best practices for some PR features in GitHub, e.g. regarding the "Resolve" button or the "Draft" mode.

Now this PR should be complete.

2021-05-06 09:33 UTC, merged