MAINT: Remove Selenium dependency and harmonize storage locations
ContactEngineering/TopoBank pull request #802
Opened 2022-03-01 10:26 UTC by pastewka

This PR will address:
- Selenium dependency, #787 
- Storage locations, #801

2022-03-06 13:01 UTC, pastewka commented
@mcrot - I've run into a problem and need your advise here:

Both `Topography` and `Analysis` models now have a `storage_prefix` attribute that defines the prefix in the storage system. It need to know the `id` of the model to generate the prefix. The `id` is only known once the model has been saved to the database. This cause problems in the tests, where the model is initialized with some data file and at this point the `id` is not yet known. The solutions to this that I've found are:

- Switch the `id` field to a UUID (see here: https://stackoverflow.com/questions/41428290/django-instance-id-none-when-uploading-image).
- Overload the `save` method (see here: https://stackoverflow.com/questions/9968532/django-admin-file-upload-with-current-model-id)

I'd actually be in favor of using UUIDs for primary keys as this may have security advantages (you cannot guess an id). It may also help here: #307 . However switching to UUIDs would require a larger migration of the database.

2022-03-06 20:35 UTC, pastewka commented
I've implemented option 2 and that seems to work

2022-03-06 22:27 UTC, pastewka commented
Hi @mcrot - this is ready for your review

2022-03-30 08:36 UTC, mcrot commented on topobank/manager/signals.py
> +    squeezed_datafile_path = instance.datafile.name
Should this be `instance.squeezed_datafile.name`?

2022-03-30 08:38 UTC, mcrot commented on topobank/manager/signals.py
> +    if datafile_path is not None and not datafile_path.startswith(instance.storage_prefix):
Why has this been doubled?

2022-03-30 08:46 UTC, mcrot requested changes
Please review my questions on `signals.py`.

2022-03-30 13:10 UTC, pastewka commented on topobank/manager/signals.py
> +    if datafile_path is not None and not datafile_path.startswith(instance.storage_prefix):
Can be removed

2022-03-30 13:36 UTC, mcrot approved these changes

2022-03-31 20:58 UTC, merged