Performance tweaks
ContactEngineering/TopoBank pull request #856
Opened 2022-07-07 15:24 UTC by pastewka

Addresses performance issues with analysis - #841 #847

2022-07-07 15:46 UTC, pastewka commented
Hi @mcrot - here are the performance tweaks. They should get rid of most of the bottlenecks.

2022-07-08 05:43 UTC, pastewka commented
Hi @mcrot - I've removed package updates from this PR. Note that some analysis results will need to be recomputed. (Those that use `PlotCardView`.)

2022-07-08 09:26 UTC, mcrot commented on config/settings/local.py
> -INSTALLED_APPS += ['debug_toolbar']  # noqa F405
Is it intended that we disable the debug tool for development by default?
Or is this just a left-over from debugging?

2022-07-08 09:45 UTC, mcrot requested changes
Looks great! I'm looking forward to see this in production.

Two things:
- Shall we really disable the debug toolbar for development by default?
- The test for split dictionaries should be extended by the use of the supplementary dict.

2022-07-08 11:25 UTC, mcrot approved these changes
This can be merged. If there are no string reasons against, I would keep the debug toolbar.

2022-07-08 15:43 UTC, pastewka commented on config/settings/local.py
> -INSTALLED_APPS += ['debug_toolbar']  # noqa F405
I am readding it

2022-07-11 07:54 UTC, mcrot approved these changes

2022-07-11 08:15 UTC, merged